FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json ../../package.json ../../package-lock.json* ./
RUN npm install --legacy-peer-deps --silent && npm cache clean --force

COPY apps/api/package.json ./package.json
COPY apps/api/ ./
RUN npm install --silent && npm cache clean --force
RUN npm run build

EXPOSE 3000
CMD ["node", "dist/main.js"] 