# This file tells Render how to build and deploy your application.
# For more details, see the Render documentation: https://render.com/docs/yaml-spec

databases:
  # 1. PostgreSQL Database
  - name: dialer-db
    databaseName: dialer_db
    plan: free # Note: free plans may spin down due to inactivity.

services:
  # 2. Redis Cache
  - type: redis
    name: dialer-redis
    plan: free
    ipAllowList: [] # Allows access from other services in your Render account

  # 3. Backend API (NestJS)
  - type: web
    name: api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dialer-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: dialer-redis
          property: connectionString
      # --- Secrets (set in Render UI) ---
      - key: JWT_SECRET
        generateValue: true
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # 4. Frontend Web App (React + Vite)
  - type: web
    name: web
    plan: free
    runtime: node
    buildCommand: |
      npm install
      npm run build --workspace=apps/web
    startCommand: "npm install -g serve && serve -s ./apps/web/dist"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: api
          property: url

  # 5. Frontend Web App (React + Vite)
  - type: static
    name: web
    plan: free
    buildCommand: |
      npm install
      npm run build --workspace=apps/web
    publishDir: ./apps/web/dist
    routes:
      # Proxy /api requests to the backend service.
      # The .onrender.com URL is created automatically.
      - type: rewrite
        source: /api/:path*
        destination: https://api.onrender.com/:path*
      # Rewrite all other requests to index.html for React Router.
      - type: rewrite
        source: /*
        destination: /index.html 